api = "0.2"

[buildpack]
  homepage = "https://github.com/accrazed/node-run-script"
  id = "accrazed/node-run-script"
  name = "Paketo Node-Run-Script Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
