api = "0.2"

[buildpack]
  id = "paketo-buildpacks/node-run-script"
  homepage = "https://github.com/paketo-buildpacks/node-run-script"
  name = "Paketo Node-Run-Script Buildpack"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[metadata]
  include-files = ["bin/run","bin/build","bin/detect","buildpack.toml"]
  pre-package = "./scripts/build.sh"
